### ISSUE TITLE
missing requirement Dynamicweb version for Swift 1.7, 1.8 and 1.9 in README.md

### ISSUE THREAD

**Issue by x-mfh** [dynamicweb/Swift#10]
As the title states - the README.md hasn't been updated with new requirements for Dynamicweb version since Swift 1.6.1. 
And there's no mention of the new releases on https://doc.dynamicweb.com/downloads/swift :)

**Comment by misterwinther** [comment]
@x-mfh Great catch :) We will update this in the coming realease.

**Comment by misterwinther** [comment]
@x-mfh We have updated the README file and the doc site :) Thanks for the heads up!
