### ISSUE TITLE
Product page link on Navigation>Utilities>Cart>Checkout anonymous>Checkout results in bad link.

### ISSUE THREAD

**Issue by x-mfh** [dynamicweb/Swift#11]
Hi DW,

As the title mentions, the link to product page on Navigation>Utilities>Cart>Checkout anonymous>Checkout always prepend "Default.aspx?ID=" resulting in a bad link.

![image](https://user-images.githubusercontent.com/12151202/171795277-5bd7955f-a508-4a96-b02d-bc71d870ca95.png)

![image](https://user-images.githubusercontent.com/12151202/171795932-d20ca2b2-6beb-4a40-95af-0fe066cb478c.png)

looks like these other files are effected too.
![image](https://user-images.githubusercontent.com/12151202/171795752-85fe97ca-d500-4b6a-a2d6-134d7a7163f7.png)

Best regards,
Mikkel H

**Comment by x-mfh** [comment]
Just as a note - it auto fills with "Default.aspx?ID=7448" when selecting the page with the Internal link button on the right in picture 1. But you can "fix" it with removing the "Default.aspx?id=" yourself.

The cart link just below the link in picture 1 works fine with the "Default.aspx?ID=7449" link, so there's an inconsistency with the linking

**Comment by misterwinther** [comment]
@x-mfh Great catch! And thank your for the easy fix suggestion. We will see to this being fixed :)

**Comment by misterwinther** [comment]
@x-mfh By the way - within a short time span - we will release with a fix for this. It's a part of a larger chunk of improvements to how rendering of PDP and links (also breadcrumbs) will behave.

**Comment by misterwinther** [comment]
@x-mfh Would you say that this has been resolved?
