### ISSUE TITLE
Row templates do not open in Visual editor and cant be sorted as result

### ISSUE THREAD

**Issue by cf-skabertrang** [dynamicweb/Swift#18]
Hi.
The row templates cant be opened in the visual editor.
the Page and paragraph templates is working, so i guess there is a bug with the row templates ?

![image](https://user-images.githubusercontent.com/107463155/178427875-7ed8f2e2-ec85-467d-8db0-8e23e9482fa4.png)

**Comment by KarstenThuen** [comment]
Hi 

Thanks for notifying us on this bug. We have recently solved it on bug #8095 - The fix will be in the first release after the summer vacation.

Best regards
Karsten Thuen
