### ISSUE TITLE
EditProfile.cshtml having novalidate on the form

### ISSUE THREAD

**Issue by x-mfh** [dynamicweb/Swift#19]
Hi DW,

Is there a reason EditProfile adds a novalidate tag to the form, which disables all "requires" attributes on the input fields?

https://github.com/dynamicweb/Swift/blob/main/Swift/Files/Templates/Designs/Swift/UserManagement/ViewProfile/EditProfile.cshtml#L19

when in /Address, it's not used
https://github.com/dynamicweb/Swift/blob/main/Swift/Files/Templates/Designs/Swift/UserManagement/Addresses/AddAddress.cshtml#L34
https://github.com/dynamicweb/Swift/blob/main/Swift/Files/Templates/Designs/Swift/UserManagement/Addresses/ManageAddresses.cshtml#L39

It results in only the email required being hit, but it can't find any where to add other fields to the validation when editing the user profile

![image](https://user-images.githubusercontent.com/12151202/193240882-d161ab62-57bf-4b77-b74c-70cc0dcd95f7.png)

Best regards,
Mikkel Hammer

**Comment by misterwinther** [comment]
@x-mfh Yes - it's intentional because we want the server to handle the validation, and not the browser 😄 

//Stefan
