### ISSUE TITLE
Defail.aspx in Querypublisher

### ISSUE THREAD

**Issue by kmapico** [dynamicweb/Swift#24]
Hi DW,

When using the new combined product and content search, I found what seems to be a typo in the file Content.cshtml in Swift/QueryPublisher.

The link to the content page is written like /Defail.aspx?ID=@pageId, where I would suppose it should be /Default.aspx?ID=@pageId

--
Best regards
Kurt Moskjaer Andersen

**Comment by misterwinther** [comment]
Hi @kmapico 
Thanks for the heads up - I will put our QA to the task :)

//Stefan

**Comment by misterwinther** [comment]
@kmapico this has been solved in recent commits :)

//Stefan
