### ISSUE TITLE
Using the templates - version 1.19

### ISSUE THREAD

**Issue by joelmandell** [dynamicweb/Swift#25]
Hi,
I tried to use DW9 in an ASP.NET Core project (because .NET Standard 2.0, it should work right?).
When using Swift 1.19 in the project, I get a lot of compilation errors because the templates is using @helper for, which does not work in .NET Core and forwards.

I was of the impression that 1.19 did contain adjustments in order to work for DW10 (and .NET5 and further).
In release log it says something about a conversion tool but I cannot find it in the project repo?
Is it maybe a static analyzer that converts the templates only if is used in an DW10 project?

**Comment by nicped** [comment]
Almost work. ASP.NET core Razor and ASP.NET 4 razor is almost identical, but differs in terms of what is supported - i.e. Helpers which do not exist in .NET Core - this is not Dynamicweb related!

So you cannot do what you are trying to.

The Swift templates are compatible using Dynamicweb 10 template compatibility settings:
![image](https://user-images.githubusercontent.com/3715307/229100971-69701077-d9f5-4ca9-b27c-f7b5a5b20d98.png)

Using these settings, Dynamicweb will automatically convert helpers to the new .NET core format needed for Dynamicweb 10.

You might also find a bit of insights here:
[https://github.com/dynamicweb/NetStandardIntellisenseProject](https://github.com/dynamicweb/NetStandardIntellisenseProject)
