### ISSUE TITLE
Generate the needed tables

### ISSUE THREAD

**Issue by joelmandell** [dynamicweb/Swift#27]
Hi.
Does it exist a script to generate the tables on an existing database after a dw10-generated template project?
Or do I need to download the db-image and reconfigure settings on my dw10-proj to use that Swift-db instead?

If so I would propose it as a feature request to have a script to generate the tables like ItemType_Swift_Page and so on...

**Comment by nicped** [comment]
After installation of the default Dynamicweb database, you can install swift templates and item types. When installing itemtypes (The XML files), the database tables will automatically be created. The new tables will contain no data - so the page structure, component library and Swift setup will be missing and you need to set that up your self.

So it is probably easier to attach a Swift database instead.

**Comment by joelmandell** [comment]
Thx @nicped
