### ISSUE TITLE
Sorting for paging defaults to Relevance, not to module sorting

### ISSUE THREAD

**Issue by Imar** [dynamicweb/Swift#28]
Hi there,
When paging products, the default sorting for the next page is hard-coded to "Relevance". This causes issues when the default sort is overwritten on the module.

Steps to reproduce:

1. On the catalog module, set up sorting as follows:

![image](https://github.com/dynamicweb/Swift/assets/4247911/c8820ec0-4ff5-498a-a0fc-6585a022011b)

2. Browse to the products page. The first 25 products or so are sorted correctly by creation date.

3. Click the Next page link. 

**Expected results** 
I get the next page of records with all products still sorted by creation date in descending order.

**Actual results**
The sorting is now off as it uses Relevance in the query string for the next page instead of "-created"

/products?PageSize=42&**SortBy=Relevance**&RequestType=UpdateList

**Comment by nicped** [comment]
Bug devops#14444
https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_git/Swift/pullrequest/9405
