### ISSUE TITLE
Error executing template "Designs/Swift/Paragraph/Swift_Accordion.cshtml"

### ISSUE THREAD

**Issue by BraxTh** [dynamicweb/Swift#29]
Database: Swift_20240129
Files: Swift_v1.25.1

Fresh setup with no changes

There is a problem with Product -> Product card B in the standard Swift setup. 
Looks like the Accordion template is broken:

Error executing template "Designs/Swift/Paragraph/Swift_Accordion.cshtml"

![image](https://github.com/dynamicweb/Swift/assets/100278186/ab011927-c0ab-43be-8f9f-169ce756a3e7)
![image](https://github.com/dynamicweb/Swift/assets/100278186/cad924ce-256f-4786-b6db-3f473f20e5c3)

**Comment by misterwinther** [comment]
Hi @BraxTh,

This is due to a deprecated itemtype. This has been described in release notes :)

Newest version + DB does not have this issue.

Hope this sorts things out for you.

/Stefan
