### ISSUE TITLE
Missing files for mini favorites page

### ISSUE THREAD

**Issue by LasseLarsenSP** [dynamicweb/Swift#3]
In the Guide for setting up favorite lists in swift, the setup of a ["Mini favorites page" ](https://doc.dynamicweb.com/swift/setup-project/ecommerce-design/favorites-lists)service is mentioned. As of 1.4 i do not have the option to choose that service.
[](https://doc.dynamicweb.com/swift/setup-project/ecommerce-design/favorites-lists)

![billede](https://user-images.githubusercontent.com/96050596/145795338-c16dc851-ab2b-4953-97a7-1eca2e7830e3.png)

In [Swift/Swift.csproj](https://github.com/dynamicweb/Swift/blob/049124257d0e013a1b4a7e71f437fd1906ed65bd/Swift/Swift.csproj) i can see that there are references to[ "Files\System\Items\ItemType_Swift_MiniFavorites.xml"](https://github.com/dynamicweb/Swift/blob/049124257d0e013a1b4a7e71f437fd1906ed65bd/Swift/Swift.csproj#L65) and ["Files\Templates\Designs\Swift\Swift_MiniFavorites.cshtml"](https://github.com/dynamicweb/Swift/blob/049124257d0e013a1b4a7e71f437fd1906ed65bd/Swift/Swift.csproj#L984), that sounds like they could be related. When searching for these files they seem to be missing in the project.

**Comment by misterwinther** [comment]
Hi @LasseLarsenSP 
Great catch 👍  
We've changed the way setup works. The documentation is missing an update.

So what you need to do is:
- Create regular page (not Mini Favorites - as it is not available anymore)
- Attach product catalog app w/ correct template for favorites

You should be up and running in no time 😄

**Comment by LasseLarsenSP** [comment]
Hey @misterwinther 

Thank you for the help. I can see that the documentation is already updated, i will give it a try 😄
