### ISSUE TITLE
selectedDetailPage improve null checks

### ISSUE THREAD

**Issue by misterwinther** [dynamicweb/Swift#8]

**Comment by x-mfh** [comment]
A little more context for this issue that we have experiences so far, hope it helps.

You can fix it for type "Trending" if you select a Group under "Relation"
![image](https://user-images.githubusercontent.com/12151202/151135758-3c6462e1-0b69-4aec-a702-42888593b879.png)

But it breaks when selecting any other type, ex "Frequently bought", where the relation is not a group.
![image](https://user-images.githubusercontent.com/12151202/151136325-e7bb68b7-dcfc-4ce9-af04-54eaa34d7602.png)

**Comment by misterwinther** [comment]
@x-mfh Super! Thank you for clarifying

**Comment by misterwinther** [comment]
@x-mfh please see referenced commit for resolving

**Comment by x-mfh** [comment]
@misterwinther Didn't think of searching for more occurrences, my bad :)
Thanks for the quick fix! 🚀

**Comment by misterwinther** [comment]
@x-mfh No problem :) Let us know if this is not resolving the bug issues. Please re-open if not the case.
