### ISSUE TITLE
Uncaught (in promise) TypeError when adding addToFavorites button on productslider for frontpage

### ISSUE THREAD

**Issue by BeatRax** [dynamicweb/Swift#9]
Trying to add a addToFavorites button on the productSlider on the frontpage. Getting the following error running a Swift 1.5.0 and DW 9.13.0
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getAttribute')

I have added the exact same code from productSlider file into my own produtsliderCustom file since I had to add a add to cart functionality and the add to fav. 

in the console the errors are 
![image](https://user-images.githubusercontent.com/24681530/151951857-6cc15541-9e5f-4441-abce-fcd1944f23a8.png)
![image](https://user-images.githubusercontent.com/24681530/151951907-f189fab8-2964-4d2a-a960-f998ba0abfff.png)

- In productSlider.cshtml the code for favorites is 

	favoriteParameters = new Dictionary<string, object>();
	if (!anonymousUser)
	{
		int defaultFavoriteListId = 0;

		IEnumerable<FavoriteList> favoreiteLists = Pageview.User.GetFavoriteLists();
		int favoriteListsTotal = favoreiteLists.Count();

		if (favoreiteLists.Count() == 1) {
			foreach (FavoriteList list in favoreiteLists) {
				defaultFavoriteListId = list.ListId;
			}
		}
		
		favoriteParameters.Add("ListId", defaultFavoriteListId);
		favoriteParameters.Add("ListTotal", favoriteListsTotal);
	}
	
This snippet call the toggleFavorites.cshtml file that triggers the event in the button. 
	
if (!anonymousUser && product.VariantInfo.VariantInfo == null) {
		<div class="position-absolute top-0 end-0 my-3" style="z-index: 2">
			@RenderPartial("Components/ToggleFavorite.cshtml", product, favoriteParameters)
		</div>
	}

- In _favorites.js
the error is triggered at the location marked with the arrow 
![image](https://user-images.githubusercontent.com/24681530/151952666-1a7374e8-4eaf-4b7f-9d34-2a5688812e6c.png)

Hope this is enough to go on !

**Comment by misterwinther** [comment]
@BeatRax Thanks for reaching out. We will look into this.

**Comment by jentjohansen** [comment]
@BeatRax The bug is registered, has been fixed and now send to QA

**Comment by misterwinther** [comment]
@BeatRax a fix is provided in https://github.com/dynamicweb/Swift/commit/cfb079774f3948d317ae8915286f7a96a90b6ab0. Please reopen this issue if the fix is not sufficient.
